yarnPath: .yarn/releases/yarn-4.5.3.cjs
nodeLinker: node-modules

# packageExtensions:
#   "markdown-it@*":
#     dependencies:
#       punycode: "^2.3.1"

packageExtensions:
  "expo-image@*":
    dependencies:
      "@react-native/assets-registry": "0.76.5"
