yarnPath: .yarn/releases/yarn-4.5.3.cjs
nodeLinker: node-modules

packageExtensions:
  "react-native-markdown-display@*":
    dependencies:
      "markdown-it": "^14.1.0"
  "one@*":
    dependencies:
      "react-native-screens": "4.9.2"
