nodeLinker: node-modules

packageExtensions:
  one@*:
    dependencies:
      react-native-screens: 4.9.2
  react-native-markdown-display@*:
    dependencies:
      markdown-it: ^14.1.0

yarnPath: .yarn/releases/yarn-4.9.1.cjs
