import { optimizeFilterFile } from "./filter";
import { FieldEnum, FilterFile } from "./schema";

export const filterPolitics: FilterFile = {
  spec_version: "lemmy-filters/1.0",
  options: {
    normalize: "nfkc_casefold",
    strip_diacritics: true,
    max_body_chars: 50000,
  },
  rules: [
    {
      name: "Hide political communitites",
      any: [
        {
          field: FieldEnum.community_name,
          op: "substring",
          pattern: "political",
        },
        {
          field: FieldEnum.community_name,
          op: "substring",
          pattern: "politics",
        },
        {
          field: FieldEnum.community_name,
          op: "substring",
          pattern: "trump",
        },
        {
          field: FieldEnum.community_name,
          op: "substring",
          pattern: "policeproblem",
        },
        {
          field: FieldEnum.community_name,
          op: "substring",
          pattern: "50501.chat",
        },
      ],
      action: "hide",
    },
    {
      name: "Political persons",
      any: [
        { field: FieldEnum.title, op: "substring", pattern: "epstein files" },
        { field: FieldEnum.title, op: "substring", pattern: "charlie kirk" },
        { field: FieldEnum.title, op: "substring", pattern: "pete hegseth" },
        { field: FieldEnum.title, op: "word", pattern: "hegseth" },
        {
          field: FieldEnum.title,
          op: "substring",
          pattern: "karoline leavitt",
        },
        { field: FieldEnum.title, op: "word", pattern: "trump" },
        { field: FieldEnum.title, op: "word", pattern: "vance" },
      ],
      action: "hide",
    },
    {
      name: "Political words",
      any: [
        { field: FieldEnum.title, op: "substring", pattern: "democrat" },
        { field: FieldEnum.title, op: "substring", pattern: "republican" },
        { field: FieldEnum.title, op: "word", pattern: "maga" },
        { field: FieldEnum.title, op: "substring", pattern: "radical left" },
      ],
      action: "hide",
    },
    {
      name: "ICE",
      all: [
        { field: FieldEnum.title, op: "substring", pattern: "ice" },
        {
          any: [
            { field: FieldEnum.title, op: "word", pattern: "detention" },
            { field: FieldEnum.title, op: "word", pattern: "detain" },
            { field: FieldEnum.title, op: "substring", pattern: "deport" },
            { field: FieldEnum.title, op: "substring", pattern: "kidnap" },
            { field: FieldEnum.title, op: "substring", pattern: "arrest" },
            { field: FieldEnum.title, op: "substring", pattern: "raid" },
          ],
        },
      ],
      action: "hide",
    },
    {
      name: "Location scoped",
      all: [
        {
          any: [
            { field: FieldEnum.title, op: "substring", pattern: "u.s." },
            // US States
            { field: FieldEnum.title, op: "word", pattern: "alabama" },
            { field: FieldEnum.title, op: "word", pattern: "alaska" },
            { field: FieldEnum.title, op: "word", pattern: "arizona" },
            { field: FieldEnum.title, op: "word", pattern: "arkansas" },
            { field: FieldEnum.title, op: "word", pattern: "california" },
            { field: FieldEnum.title, op: "word", pattern: "colorado" },
            { field: FieldEnum.title, op: "word", pattern: "connecticut" },
            { field: FieldEnum.title, op: "word", pattern: "delaware" },
            { field: FieldEnum.title, op: "word", pattern: "florida" },
            { field: FieldEnum.title, op: "word", pattern: "georgia" },
            { field: FieldEnum.title, op: "word", pattern: "hawaii" },
            { field: FieldEnum.title, op: "word", pattern: "idaho" },
            { field: FieldEnum.title, op: "word", pattern: "illinois" },
            { field: FieldEnum.title, op: "word", pattern: "indiana" },
            { field: FieldEnum.title, op: "word", pattern: "iowa" },
            { field: FieldEnum.title, op: "word", pattern: "kansas" },
            { field: FieldEnum.title, op: "word", pattern: "kentucky" },
            { field: FieldEnum.title, op: "word", pattern: "louisiana" },
            { field: FieldEnum.title, op: "word", pattern: "maine" },
            { field: FieldEnum.title, op: "word", pattern: "maryland" },
            { field: FieldEnum.title, op: "word", pattern: "massachusetts" },
            { field: FieldEnum.title, op: "word", pattern: "michigan" },
            { field: FieldEnum.title, op: "word", pattern: "minnesota" },
            { field: FieldEnum.title, op: "word", pattern: "mississippi" },
            { field: FieldEnum.title, op: "word", pattern: "missouri" },
            { field: FieldEnum.title, op: "word", pattern: "montana" },
            { field: FieldEnum.title, op: "word", pattern: "nebraska" },
            { field: FieldEnum.title, op: "word", pattern: "nevada" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "new hampshire",
            },
            { field: FieldEnum.title, op: "substring", pattern: "new jersey" },
            { field: FieldEnum.title, op: "substring", pattern: "new mexico" },
            { field: FieldEnum.title, op: "substring", pattern: "new york" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "north carolina",
            },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "north dakota",
            },
            { field: FieldEnum.title, op: "word", pattern: "ohio" },
            { field: FieldEnum.title, op: "word", pattern: "oklahoma" },
            { field: FieldEnum.title, op: "word", pattern: "oregon" },
            { field: FieldEnum.title, op: "word", pattern: "pennsylvania" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "rhode island",
            },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "south carolina",
            },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "south dakota",
            },
            { field: FieldEnum.title, op: "word", pattern: "tennessee" },
            { field: FieldEnum.title, op: "word", pattern: "texas" },
            { field: FieldEnum.title, op: "word", pattern: "utah" },
            { field: FieldEnum.title, op: "word", pattern: "vermont" },
            { field: FieldEnum.title, op: "word", pattern: "virginia" },
            { field: FieldEnum.title, op: "word", pattern: "washington" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "west virginia",
            },
            { field: FieldEnum.title, op: "word", pattern: "wisconsin" },
            { field: FieldEnum.title, op: "word", pattern: "wyoming" },
            // Cities
            { field: FieldEnum.title, op: "substring", pattern: "new york" },
            { field: FieldEnum.title, op: "substring", pattern: "los angeles" },
            { field: FieldEnum.title, op: "word", pattern: "chicago" },
            { field: FieldEnum.title, op: "word", pattern: "houston" },
            { field: FieldEnum.title, op: "word", pattern: "phoenix" },
            { field: FieldEnum.title, op: "word", pattern: "philadelphia" },
            { field: FieldEnum.title, op: "substring", pattern: "san antonio" },
            { field: FieldEnum.title, op: "substring", pattern: "san diego" },
            { field: FieldEnum.title, op: "word", pattern: "dallas" },
            { field: FieldEnum.title, op: "word", pattern: "jacksonville" },
            { field: FieldEnum.title, op: "substring", pattern: "fort worth" },
            { field: FieldEnum.title, op: "substring", pattern: "san jose" },
            { field: FieldEnum.title, op: "word", pattern: "austin" },
            { field: FieldEnum.title, op: "word", pattern: "charlotte" },
            { field: FieldEnum.title, op: "word", pattern: "columbus" },
            { field: FieldEnum.title, op: "word", pattern: "indianapolis" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "san francisco",
            },
            { field: FieldEnum.title, op: "word", pattern: "seattle" },
            { field: FieldEnum.title, op: "word", pattern: "denver" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "oklahoma city",
            },
            { field: FieldEnum.title, op: "word", pattern: "nashville" },
            { field: FieldEnum.title, op: "word", pattern: "washington" },
            { field: FieldEnum.title, op: "substring", pattern: "el paso" },
            { field: FieldEnum.title, op: "substring", pattern: "las vegas" },
            { field: FieldEnum.title, op: "word", pattern: "boston" },
            { field: FieldEnum.title, op: "word", pattern: "detroit" },
            { field: FieldEnum.title, op: "word", pattern: "louisville" },
            { field: FieldEnum.title, op: "word", pattern: "portland" },
            { field: FieldEnum.title, op: "word", pattern: "memphis" },
            { field: FieldEnum.title, op: "word", pattern: "baltimore" },
            { field: FieldEnum.title, op: "word", pattern: "milwaukee" },
            { field: FieldEnum.title, op: "word", pattern: "albuquerque" },
            { field: FieldEnum.title, op: "word", pattern: "tucson" },
            { field: FieldEnum.title, op: "word", pattern: "fresno" },
            { field: FieldEnum.title, op: "word", pattern: "sacramento" },
            { field: FieldEnum.title, op: "word", pattern: "atlanta" },
            { field: FieldEnum.title, op: "word", pattern: "mesa" },
            { field: FieldEnum.title, op: "substring", pattern: "kansas city" },
            { field: FieldEnum.title, op: "word", pattern: "raleigh" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "colorado springs",
            },
            { field: FieldEnum.title, op: "word", pattern: "omaha" },
            { field: FieldEnum.title, op: "word", pattern: "miami" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "virginia beach",
            },
            { field: FieldEnum.title, op: "substring", pattern: "long beach" },
            { field: FieldEnum.title, op: "word", pattern: "oakland" },
            { field: FieldEnum.title, op: "word", pattern: "minneapolis" },
            { field: FieldEnum.title, op: "word", pattern: "bakersfield" },
            { field: FieldEnum.title, op: "word", pattern: "tulsa" },
            { field: FieldEnum.title, op: "word", pattern: "tampa" },
            { field: FieldEnum.title, op: "word", pattern: "arlington" },
          ],
        },
        {
          any: [
            { field: FieldEnum.title, op: "substring", pattern: "shoot up" },
            { field: FieldEnum.title, op: "word", pattern: "shooting" },
            { field: FieldEnum.title, op: "word", pattern: "shooter" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "border agent",
            },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "border officer",
            },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "detension center",
            },
            { field: FieldEnum.title, op: "substring", pattern: "police" },
            {
              field: FieldEnum.title,
              op: "substring",
              pattern: "law enforcement",
            },
          ],
        },
      ],
      action: "hide",
    },
  ],
};
