name: PR - Deploy Blorp Brach Build

on: 
  pull_request:

permissions:
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install netlify
        run: npm i -g netlify-cli@18

      - name: 'Deploy to Netlify'
        id: netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: false
          deploy_alias: "pr-${{ github.event.pull_request.number }}"
          build_command: "yarn build"
          build_directory: "dist"
          install_command: "yarn install --immutable"

      - name: Create or Update PR Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **PR Preview Updated!**
            
            🔗 [View Live Preview](${{ env.NETLIFY_PREVIEW_URL }})
          edit-mode: replace
