# .github/workflows/docker-on-tag.yml
name: Build & Push Docker Image on Tag

on:
  push:
    # Trigger only on tags like "v1.2.3"
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write   # needed to push to ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Normalize lowercase vars
        id: vars
        run: |
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "ref_name=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Set up QEMU (optional, for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (GHCR + Docker Hub)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.owner_lc }}/blorp:${{ env.ref_name }}
            ghcr.io/${{ env.owner_lc }}/blorp:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blorp:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blorp:latest
