# .github/workflows/docker-on-tag.yml
name: Build & Push Docker Image on Tag

on:
  push:
    # Trigger only on tags like "v1.2.3"
    # tags:
    #   - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU (optional, for multi‑arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blorp:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blorp:latest
