
name: PR Preview Build

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write  # Needed to comment on the PR

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'yarn'

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Build Tamagui One app (without Sentry)
        run: yarn build:web

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          PREVIEW_URL=$(netlify deploy --dir=dist/client --json | jq -r .deploy_url)
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Comment PR with Preview Link
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 **PR Preview Available!**
            
            🔗 [View Live Preview](${{ env.PREVIEW_URL }})
